database:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    user: vote
    password: vote
    properties:
        hibernate.c3p0.max_size: 5
        hibernate.c3p0.min_size: 1
        hibernate.c3p0.timeout: 600
        hibernate.c3p0.max_statements: 100
        hibernate.c3p0.acquire_increment: 5
        hibernate.c3p0.idle_test_period: 60
        hibernate.show_sql: true

http:
    port: 8888
logging:
    level: INFO
    loggers:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    console:
        level: ALL